aerospike/aerospike-monitoring

config/grafana/dashboards/alerts.json
config/grafana/dashboards/cluster.json
config/grafana/dashboards/latency.json
config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json
config/grafana/dashboards/xdr.json

To be merged with [Aerospike Prometheus Exporter 1.1.0 release PR](https://github.com/aerospike/aerospike-prometheus-exporter/pull/28)
- [PROD-1133] - Fix primary index dashboard to be in MiB/GiB
- [PROD-1131] - Adjust Grafana refresh rate to 1 minute
- [PROD-1134] & [PROD-1135] - Add description to each dashboard panel
- [PROD-1185] - Add clock_skew_stop_writes to namespace view dashboard
- [PROD-1132] & [PROD-1130] - Add new latency dashboard for the new histograms change on Aerospike Prometheus Exporter
- [PROD-1180] - Remove `aerospike_node_info` metric
- Consider both migrate tx and rx in migrations remaining panel within cluster and namespace view
- Add `client_udf_timeout` to UDFs (TPS) panel in namespace view
[PROD-1133]: https://aerospike.atlassian.net/browse/PROD-1133 …

Dashboard fixes and improvements

---

config/grafana/dashboards/latency.json

The aerospike_latencies_${operation}_${latencytimeunit}_bucket metrics is an ops/sec gauge
so we don't need to apply a rate on it

Correct 90 percentile latency computation on grafana latency dashboard

---

CHANGELOG.md
config/grafana/dashboards/jobs.json
config/grafana/dashboards/sindex.json

- [TOOLS-1956] - Add `Jobs View` and `Secondary Index View` dashboards
- [TOOLS-1946] - Add support for per-job scan and query statistics
- [TOOLS-1947] - Add support for secondary index statistics
[TOOLS-1956]: https://aerospike.atlassian.net/browse/TOOLS-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TOOLS-1946]: https://aerospike.atlassian.net/browse/TOOLS-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TOOLS-1947]: https://aerospike.atlassian.net/browse/TOOLS-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Aerospike Monitoring v1.4.0 Release

---

config/grafana/dashboards/latency.json

Support batch-index bucket and count metrics. EX: aerospike_latencies_batch_index_us_bucket and aerospike_latencies_batch_index_us_count

[TOOLS-2069] Add batch-index latency panels.

---

config/grafana/dashboards/latency.json

This replaces the current latency panels with those similar to what ACMS uses. @MicahCarrick ( I can't find you in the reviewers list so mentioning you here)
Below are some screenshots of the changed dashboards.

Replace latency panels with heat map and percentiles.

---

config/grafana/dashboards/alerts.json
config/grafana/dashboards/cluster.json
config/grafana/dashboards/exporters.json
config/grafana/dashboards/jobs.json
config/grafana/dashboards/latency.json
config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json
config/grafana/dashboards/sindex.json
config/grafana/dashboards/users.json
config/grafana/dashboards/xdr.json

**Problem:** 
I have already installed Prometheus and Grafana. I want to use these stack for monitoring aerospike.
I installed Aerospike with helm chart to my Kubernetes cluster. When I install aerospike with diffrent name I saw none of the metrics were working. The `job` is used everwhere statically.
`sum(aerospike_namespace_stop_writes{job="aerospike", cluster_name=~"$cluster", service=~"$node|$^", ns=~"$namespace|$^"})`
**Solution:**
Then I added new variable name `job_name` and I used `job` dynamically.

feat: added job_name variable to grafana dashboards

---

config/grafana/dashboards/set.json

This adds a new set dashboard for the set quotas features (and a few other metrics not on a dashboard currently).

OM-18 Set level dashboard

---

config/grafana/dashboards/namespace.json

fixed bug the NSUP Cycle Duration and Cycle Deleted % we applied sum on those 2 metrics which is incorrect. instead showing Average and Max of the NSUP metrics now.

OM-61 - namespace view

---

.github/workflows/python-lint.yml
build/dashboard_schema.json
config/grafana/dashboards/jobs.json

created a simple schema for dashboard validation 
created a GitHub Action which uses python based "jsonschema-cli" tool to validate dashboard against schema during push/pull-request, this command executes against each dashboard json file

Om 59 - added a dashboard linter

---

config/grafana/dashboards/namespace.json

modified the namespace-view dashboard, added a new row at the bottom displaying the defrag related configs and metrics, 
storage_engine_defrag_sleep
storage_engine_defrag_lwm_pct
storage_engine_file_defrag_reads (or) storage_engine_device_defrag_reads
storage_engine_file_defrag_writes (or) storage_engine_device_defrag_writes
storage_engine_file_defrag_q (or) storage_engine_device_defrag_q

Om 62 - Defrag Q

---

config/grafana/dashboards/usecases/rolling_restart.json
config/grafana/provisioning/dashboards/all.yaml

this is a new dashboard covers key metrics to be monitored during a restart of a node, in any usecase like 1. upgrade, 2. issue investigation, 3. hardware issues etc.,
this covers data in 3 key pars
1. stats
2. errors
3. resources - usage & OS
in docker this dashboard is made available as part of Aerospike/Usecases folder.

OM79 - rolling-restarts usecase dashboard

---

config/grafana/dashboards/alerts.json
config/grafana/dashboards/cluster.json
config/grafana/dashboards/exporters.json
config/grafana/dashboards/geoview.json
config/grafana/dashboards/jobs.json
config/grafana/dashboards/latency.json
config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json
config/grafana/dashboards/set.json
config/grafana/dashboards/sindex.json
config/grafana/dashboards/uniquedata.json
config/grafana/dashboards/users.json
config/grafana/dashboards/xdr.json

moved - all dashboards to Gafana 9.3.x
corrected sequence of all dashboard variable in order like “Datasource”, “Job”, “Cluster”, “Node”, “Set”
fixed duplicate-panel-id in namespace view dashboard which is not-showing correct information
bug-fixes: 
fixed time-series as “range” wherever it is configured as “instant”
added job-name in queries wherever they are missing & required
removed and replaced hard-coded job-name with variable $job_name

Om82 - dashboard fixes

---

config/grafana/dashboards/alerts.json
config/grafana/dashboards/alertsview.json
config/prometheus/deprecated_aerospike_rules.yml
config/prometheus/prometheus.yml

modified Aerospike-alerts.yml to use string severity like info(1), warn(2), error(3), critical (4)
added a new alerts-view dashboard which display stats and tables for each type of alert severity with appropriate colouring
added note as deprecated in existing alerts-panel
renamed existing Aerospike-rules.yml to deprecated-aerospike-rules.yml 
updated prometheus.yml in easy-docker examples to use both *aerospike-rules.yml files with comments

OM85 - alerts rules refactor

---

config/grafana/dashboards/namespace.json
config/grafana/provisioning/datasources/all.yaml

initial checkin with all 7.0 changes
7.0 based theme to combine 6.0 and 7.0 changes while showing state, topk and time-series values

OM128 - namespace view - 7.0 changes initial commit

---

config/grafana/dashboards/set.json

added alerts, set-objects panels
modified panels according to 7.0 stat and metric changes

OM133 - set view - 7.0 initial

---

config/prometheus/aerospike_rules.yml
config/prometheus/templates/aerospike_alert_rules.template
config/prometheus/templates/alert_config_data.json

enhanced alerts to include 7.0 metrics
- added 5 alerts in namespace
- added 2 alerts in sets updated alerts template and template json values for new variables

OM130 - 7.0 alert rules - initial checkin

---

config/grafana/dashboards/secretagent/secretagent.json

this is the initial version of secret-agent dashboard

OM149 - secret agent dashboard

---

config/grafana/dashboards/cluster.json

modified dashboard with system info metrics from aerospike-prometheus-exporter
1. added swap and shmem stats
2. added a new row with resource-network displaying network retransmit, tcp open/established connections, recieve and transmit bytes.

OM167 - add system metrics

---

config/prometheus/aerospike_connector_rules.yml

`AerospikeConnectorErrors` alert `summary` was in the `labels` section for some reason, while all other alerts it is under `annotations`.

Fix summary in labels instead of annotations

---

config/grafana/dashboards/cluster.json
config/grafana/dashboards/graph/graph_service_jvmview.json
config/grafana/dashboards/graph/graph_service_view.json
config/grafana/dashboards/xdr.json

Incudes below changes,
1. Graph Service View dashboard for Gremlin stats from Graph Service 
2. Graph Service JVM View dashboard for JVM stats from Graph Service 
3. Cluster View dashboard is modified to show system stats (memory and network) from Aerospike Prometheus Exporter
4. XDR View dashboard is modified to show system stats ( only network) from Aerospike Prometheus Exporter

Dev - AMS changes for Graph Service, Cluster and XDR View dashboards

---

config/grafana/dashboards/graph/graph_service_view.json

incorporated the feedback from product and customer, Overview should aggregate all AGS instances with:
Different color lines and a legend for the node IP. Each sub-panel should display information about specific AGS instances. The same applies to scripts/second.
Include JVM metrics (currently in the “Aerospike Graph Service JVM”) into the AGS instance panel.

OM-213 - revise graph dashboard
