aerospike/aerospike-monitoring

README.md

Some yaml files indentations were malformed - this caused Prometheus and Grafana to not start

Some yaml files indentations were malformed 

---

config/grafana/dashboards/xdr.json

- Added dashboard for XDR 5.0+

[PROD-1045] - Add support for XDR 5.0 statistics

---

config/grafana/dashboards/alerts.json
config/grafana/dashboards/cluster.json
config/grafana/dashboards/latency.json
config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json
config/grafana/dashboards/xdr.json
config/prometheus/aerospike_rules.yml
examples/swarm/aerospike.conf
examples/swarm/docker-stack.yaml
examples/swarm/prometheus.yaml

- Port Dashboards to Grafana 7.2
- Make datasource configurable through a dashboard variable
- Alert when 'close to' stop writes, when node is proxying

Dashboard improvements

---

config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json

- Shows sindex count and set index populating state in namespace view
- Shows if node failed deployment best practices in node view
- Shows namespace query stats in an optional hidden panel in namespace view

[TOOLS-1785] - Add new metrics and configurations introduced in Aerospike 5.7

---

config/grafana/dashboards/cluster.json
config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json
config/grafana/dashboards/sindex.json
config/grafana/dashboards/uniquedata.json
config/prometheus/aerospike_rules.yml

this pull request includes below changes
1. NSUP metrics in Namespace view
2. Set Quota metrics in Namespace view 
3. Unique Data usage
4. Prometheus Alert rules for NSUP, Set Quota and stop-writes-sys-memory-pct

Monitoring Dashboard - March 2023 Release

---

config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json
config/grafana/dashboards/set.json
config/grafana/dashboards/sindex.json
config/grafana/dashboards/uniquedata.json

Exported secondary-index, namespace view, node view, set view and uniquedata  dashboard with the right datasource and with export option enabled
corrected the datasource name in set and secondary-index dashboards

OM37 - fixed issues identified during cloud upload

---

config/grafana/dashboards/cluster.json

fixed the display of the Migration, now showing RX and TX separately without summing. applying sum is incorrect as it doubles up the actual migration count.

Om 22 - cluster-view 

---

config/grafana/dashboards/namespace.json

- move defrag metrics to namespace row
- removed defrag row

OM76- defrag metrics fix

---

.github/workflows/python-lint.yml
config/grafana/dashboards/alertsview.json
config/grafana/dashboards/geoview.json
config/grafana/dashboards/uniquedata.json
config/grafana/provisioning/datasources/all.yaml

unique-data view - fixed bugs 1) unique-data-bytes are not displayed when geo-location is added and 2) query to honour selected namespaces
and 3) added a historical time series panel
alerts view - fixed display colour and show alerts specific to selection criteria
multi-cluster-view: fixed Grafana version to 9.x, XDR and Latencies point to respective dashboards (instead of cluster-view dashboard). added enhancement to filter using alert-severity

Om 100 - bug fixes in master-cluster-view, alerts-view and unique-data-view

---

config/grafana/dashboards/connectors/connector_jvmview.json
config/grafana/dashboards/connectors/connectorsview.json
config/prometheus/aerospike_connector_rules.yml
config/prometheus/prometheus.yml
examples/docker/docker-compose.yml
examples/docker/easy-prometheus.yml

integrated 2 connector dashboards
1. connector view across all installed connector instances
2. connector jvm view

OM107 - connector dashboard integration

---

config/grafana/dashboards/geoview.json

modified multi-cluster-view dashboard 
- to expand panels
- diagram topology to show no-data instead of , when nothing to show

OM64- multi cluster view

---

config/grafana/dashboards/usecases/all_flash.json

modified dashboard according to 7.0 metrics

OM134 - all-flash - initial 7.0 changes

---

config/grafana/dashboards/cluster.json

modified
- aerospike version panel to show multiple build details
- aerospike cluster-size to handle split-brain issue

OM136 - cluster view 7.0 changes - initial checkin

---

config/grafana/dashboards/set.json
config/grafana/dashboards/usecases/rolling_restart.json

fixed November release testing bugs

sit_nov_release - testing

---

config/grafana/dashboards/latency.json

added support for microbench marks in the dashboard
1. fixed variable queries
2. added service/node in queries

OM151 - microbench mark support in latency-view

---

config/grafana/dashboards/usecases/node_and_host.json

OM160 - bug fix

---

config/grafana/dashboards/nodeexporter/hostview.json

1. fixed job variable not shown properly
2. realigned panels
3. corrected labels

OM163 - label and panel fixes

---

config/grafana/dashboards/usecases/datacenter_comparision.json

new dashboard to compare clusters from multiple jobs ( which can be from different data-center configured to single prometheus)

OM159 - initial checkin

---

config/grafana/dashboards/graph/graph_service_view.json

added dashboard covering graph service gremlin metrics

OM108 - graph service

---

config/grafana/dashboards/graph/graph_service_jvmview.json

added a new dashboard to cover jvm metrics from graph service

OM170 - add graph service jvm dashboard

---

config/grafana/dashboards/kubernetes/kubernetes_view.json

new dashboard to display kubernetes stats using
1. kube-state-metrics
2. cadvisor

OM-185 - kubernetes stats

---

config/grafana/dashboards/usecases/batch_transactions_view.json

added a new use-case dashboard to display all batch stats like read, write, proxy, tsvc, delete etc.,

OM-183 - new usecase dashboard

---

config/grafana/dashboards/namespace.json

modified defrag panels with stripe_defrag_q, stripe_defrag_reads and stripe_defrag_writes

OM-182 - added stripe details

---

config/grafana/dashboards/usecases/sindex_summary_view.sh

added sindex summary at namespace level information as a summary view

OM-190 - secondary view use-case dashboard

---

config/grafana/dashboards/backupservice/backupserviceview.json

new dashboard for backup service

OM-195 - backup service view

---

config/grafana/dashboards/usecases/read_lru_cache_view.json

usecase dashboard to view key metrics related to read metrics

OM-196 - read / lru view dashboard

---

config/grafana/dashboards/namespace.json
config/grafana/dashboards/usecases/rolling_restart.json

added 7.1 metrics as stat / time-series
- migrate_fresh_partitions, read_errors etc.,

OM-197 - enhance namespace & rolling-restart

---

README.md

updated correct path

---

config/grafana/dashboards/graph/graph_service_view.json

added usage metrics added in graph-service 2.2.x version

OM-202 - enhance graph dashboard

---

config/grafana/dashboards/namespace.json

added 2 new metrics to namespace dashboard
- aerospike_namespace_nsup_xdr_key_busy
- aerospike_namespace_fail_xdr_key_busy

OM-207 - added 7.2 metrics to namespace dashboard

---

config/datadog/dashboards/usecases/secondary_index_summary.json

Updated query panels for rate/hr in secondary_index_summary datadog dashboard

secondary_index_summary datadog dashboard

---

config/datadog/README.md
config/datadog/dashboards/usecases/rolling_restarts.json
config/datadog/monitors/aerospike_datadog_monitors.json
config/datadog/monitors/datadog_monitors_creation.py

- Updated Rolling restarts dashboard json file by removing rate from gauge panels
- Updated aerospike_datadog_monitors.json & datadog_monitors_creation.py
- Updated README.md file for Datadog

Datadog dashboards & README file changes

---

config/grafana/dashboards/namespace.json

added mrt statistics in 8.0 to namespace view dashboard

OM-210 - mrt statistics

---

config/grafana/dashboards/cluster.json
config/grafana/dashboards/namespace.json
config/grafana/dashboards/node.json
config/grafana/dashboards/usecases/all_flash.json
config/grafana/dashboards/usecases/rolling_restart.json
config/grafana/dashboards/xdr.json

- Updated changes in Grafana dashboards such as node_view, namespace_view, xdr_view, cluster_view , rolling_restart and all flash.

Updated bug fixes in Grafana dashboards

---

config/grafana/dashboards/usecases/mrt_view.json

Usecase dashboard to show MRT metrics, MRT set specific metrics

OM-221 - MRT Usecase dashboard

---

config/grafana/dashboards/latency.json

changed the latency-unit variable to use custom ms,us values instead of reading from the metric.

OM-257 - Enhance Latency dashboard

---

config/grafana/dashboards/uniquedata.json

modified data calculation formula according to 8x version

[OM-246] - Adjust the unique data calculation formula

---

config/datadog/dashboards/cluster_view.json
config/datadog/dashboards/latency_view.json
config/datadog/dashboards/namespace_view.json
config/datadog/dashboards/node_view.json
config/datadog/dashboards/secondary_index_view.json
config/datadog/dashboards/set_view.json
config/datadog/dashboards/usecases/all_flash.json
config/datadog/dashboards/usecases/batch_transactions_view.json
config/datadog/dashboards/usecases/lru_cache_view.json
config/datadog/dashboards/usecases/rolling_restarts.json
config/datadog/dashboards/usecases/secondary_index_summary.json
config/datadog/dashboards/users_view.json
config/datadog/dashboards/xdr_view.json

Updated the Datadog dashboards JSON files with the latest changes.

[OM-243] - datadog dashboards - label and unit corrections

---

config/grafana/dashboards/backupservice/backupserviceview.json
config/prometheus/aerospike_backup_service_alerts.yml
config/prometheus/prometheus.yml
examples/docker/docker-compose.yml
examples/docker/easy-prometheus.yml

modified aerospike backup service dashboard

[OM-178] - Enhance Backup Service Dashboard
